// examples/react-nextjs/src/app/_components/TestCustomButton.tsx
'use client'

import { useQuilttConnector } from '@quiltt/react'

import { connectorId } from './quiltt-config'

export const TestCustomButton = () => {
  const { open } = useQuilttConnector(connectorId, {
    onExitSuccess: () => console.log('onExitSuccess'),
  })

  return (
    <button type="button" className="component-button" onClick={open}>
      Launch with Custom Component
    </button>
  )
}
export default TestCustomButton

// examples/vue-nuxt/src/components/test-custom-button.vue
<script setup lang="ts">

import { useQuilttConnector } from '@quiltt/vue'

const config = useRuntimeConfig()
const connectorId = config.public.quilttConnectorId

const { open } = useQuilttConnector(connectorId, {
  onExitSuccess: () => console.log('onExitSuccess'),
})
</script>

<template>
  <button type="button" class="component-button" @click="open">Launch with Custom Component</button>
</template>
