// examples/react-nextjs/src/app/_components/TestQuilttButton.tsx
'use client'

import { QuilttButton } from '@quiltt/react'

import { connectorId } from './quiltt-config'

export const TestQuilttButton = () => {
  return (
    <QuilttButton connectorId={connectorId} className="component-button">
      Launch with Component
    </QuilttButton>
  )
}
export default TestQuilttButton

// examples/vue-nuxt/src/components/test-quiltt-button.vue
<script setup lang="ts">

import { QuilttButton } from '@quiltt/vue'

const config = useRuntimeConfig()
const connectorId = config.public.quilttConnectorId
</script>

<template>
  <QuilttButton :connector-id="connectorId" as="button" class="component-button">
    Launch with Component
  </QuilttButton>
</template>
