// packages/react/test-apps/nextjs/app/components/TestQuilttButton.tsx
'use client'

import { QuilttButton } from '@quiltt/react'

export const TestQuilttButton = () => {
  return (
    <QuilttButton
      connectorId="connector"
      className="bg-purple-500 hover:bg-purple-900 text-white py-2 px-4 rounded-md"
    >
      Launch with Component
    </QuilttButton>
  )
}
export default TestQuilttButton

// examples/vue-nuxt/src/components/test-quiltt-button.vue
<script setup lang="ts">

import { QuilttButton } from '@quiltt/vue'

const config = useRuntimeConfig()
const connectorId = config.public.quilttConnectorId
</script>

<template>
  <QuilttButton :connector-id="connectorId" as="button" class="component-button">
    Launch with Component
  </QuilttButton>
</template>
