// ECMAScript/react/test-apps/nextjs/app/components/TestHTMLLauncher.tsx
'use client'

import { useQuilttConnector } from '@quiltt/react'

export const TestHTMLLauncher = () => {
  // Load the script
  useQuilttConnector()

  // Render a custom <a> launcher
  return (
    <a
      quiltt-button="connector"
      className="border-2 border-purple-500 hover:bg-purple-500 text-white py-2 px-4 rounded-full cursor-pointer"
    >
      Launch with HTML
    </a>
  )
}
export default TestHTMLLauncher

// examples/vue-nuxt/src/components/test-html-launcher.vue
<script setup lang="ts">

import { useQuilttConnector } from '@quiltt/vue'

const config = useRuntimeConfig()
const connectorId = config.public.quilttConnectorId

useQuilttConnector()
</script>

<template>
  <button type="button" :quiltt-button="connectorId" class="launcher-button">
    Launch with HTML
  </button>
</template>
