// examples/react-nextjs/src/app/_components/TestHTMLLauncher.tsx
'use client'

import { useQuilttConnector } from '@quiltt/react'

import { connectorId } from './quiltt-config'

export const TestHTMLLauncher = () => {
  useQuilttConnector()

  return (
    <button type="button" quiltt-button={connectorId} className="launcher-button">
      Launch with HTML
    </button>
  )
}
export default TestHTMLLauncher

// examples/vue-nuxt/src/components/test-html-launcher.vue
<script setup lang="ts">

import { useQuilttConnector } from '@quiltt/vue'

const config = useRuntimeConfig()
const connectorId = config.public.quilttConnectorId

useQuilttConnector()
</script>

<template>
  <button type="button" :quiltt-button="connectorId" class="launcher-button">
    Launch with HTML
  </button>
</template>
