// examples/capacitor-vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'

import { QuilttButton, QuilttConnector } from '@quiltt/capacitor/vue'

const connectorId = import.meta.env.VITE_QUILTT_CONNECTOR_ID ?? 'connector'
const appLauncherUrl = import.meta.env.VITE_APP_LAUNCHER_URL ?? 'https://app.example.com/quiltt/callback'

const events = ref<string[]>([])

const addEvent = (message: string) => {
  events.value = [message, ...events.value].slice(0, 8)
}
</script>

<template>
  <main class="app-shell">
    <header class="app-header">
      <h1>Quiltt Capacitor Vue Example</h1>
      <p>Connector ID: {{ connectorId }}</p>
    </header>

    <section class="app-content">
      <div class="panel">
        <h2>Modal Connector</h2>
        <QuilttButton
          :connector-id="connectorId"
          :app-launcher-uri="appLauncherUrl"
          class="launch-button"
          @exit-success="(metadata: any) => addEvent(`ExitSuccess: ${metadata.connectionId ?? 'n/a'}`)"
          @exit-abort="() => addEvent('ExitAbort')"
          @exit-error="() => addEvent('ExitError')"
        >
          Connect Account
        </QuilttButton>
      </div>

      <div class="panel connector-panel">
        <h2>Inline Connector</h2>
        <QuilttConnector
          :connector-id="connectorId"
          :app-launcher-uri="appLauncherUrl"
          style="width: 100%; height: 100%"
          @load="() => addEvent('Load')"
          @exit-success="(metadata: any) => addEvent(`Inline ExitSuccess: ${metadata.connectionId ?? 'n/a'}`)"
          @exit-abort="() => addEvent('Inline ExitAbort')"
          @exit-error="() => addEvent('Inline ExitError')"
        />
      </div>

      <div class="panel">
        <h2>Recent Events</h2>
        <ul class="events-list">
          <li v-if="events.length === 0">No events yet.</li>
          <li v-for="event in events" :key="event">{{ event }}</li>
        </ul>
      </div>
    </section>
  </main>
</template>

// examples/capacitor-react/src/app.tsx
import { useState } from 'react'

import { QuilttButton, QuilttConnector, QuilttProvider } from '@quiltt/capacitor/react'

const defaultToken = import.meta.env.VITE_QUILTT_AUTH_TOKEN ?? 'test-auth-token'
const defaultConnectorId = import.meta.env.VITE_QUILTT_CONNECTOR_ID ?? 'connector'
const defaultAppLauncherUri =
  import.meta.env.VITE_APP_LAUNCHER_URL ?? 'https://app.example.com/quiltt/callback'

export const App = () => {
  const [events, setEvents] = useState<string[]>([])

  const addEvent = (message: string) => {
    setEvents((prev) => [message, ...prev].slice(0, 8))
  }

  return (
    <QuilttProvider token={defaultToken}>
      <main className="app-shell">
        <header className="app-header">
          <h1>Quiltt Capacitor React Example</h1>
          <p>Connector ID: {defaultConnectorId}</p>
        </header>

        <section className="app-content">
          <div className="panel">
            <h2>Modal Connector</h2>
            <QuilttButton
              connectorId={defaultConnectorId}
              appLauncherUrl={defaultAppLauncherUri}
              onExitSuccess={(metadata) =>
                addEvent(`ExitSuccess: ${metadata.connectionId ?? 'n/a'}`)
              }
              onExitAbort={() => addEvent('ExitAbort')}
              onExitError={() => addEvent('ExitError')}
              className="launch-button"
            >
              Connect Account
            </QuilttButton>
          </div>

          <div className="panel connector-panel">
            <h2>Inline Connector</h2>
            <QuilttConnector
              connectorId={defaultConnectorId}
              appLauncherUrl={defaultAppLauncherUri}
              onLoad={() => addEvent('Load')}
              onExitSuccess={(metadata) =>
                addEvent(`Inline ExitSuccess: ${metadata.connectionId ?? 'n/a'}`)
              }
              onExitAbort={() => addEvent('Inline ExitAbort')}
              onExitError={() => addEvent('Inline ExitError')}
              style={{ width: '100%', height: '100%' }}
            />
          </div>

          <div className="panel">
            <h2>Recent Events</h2>
            <ul className="events-list">
              {events.length === 0 ? (
                <li>No events yet.</li>
              ) : (
                events.map((event) => <li key={event}>{event}</li>)
              )}
            </ul>
          </div>
        </section>
      </main>
    </QuilttProvider>
  )
}
