// examples/vue-nuxt/src/components/test-quiltt-button.vue
<script setup lang="ts">

import { QuilttButton } from '@quiltt/vue'

const config = useRuntimeConfig()
const connectorId = config.public.quilttConnectorId
</script>

<template>
  <QuilttButton :connector-id="connectorId" as="button" class="component-button">
    Launch with Component
  </QuilttButton>
</template>

// examples/react-nextjs/app/_components/TestQuilttButton.tsx
'use client'

import { QuilttButton } from '@quiltt/react'

export const TestQuilttButton = () => {
  return (
    <QuilttButton
      connectorId="connector"
      className="rounded-md bg-purple-500 px-4 py-2 text-white hover:bg-purple-900"
    >
      Launch with Component
    </QuilttButton>
  )
}
export default TestQuilttButton
