// examples/vue-nuxt/src/components/test-custom-button.vue
<script setup lang="ts">

import { useQuilttConnector } from '@quiltt/vue'

const { open } = useQuilttConnector('connector', {
  onExitSuccess: () => console.log('onExitSuccess'),
})
</script>

<template>
  <button type="button" class="component-button" @click="open">Launch with Custom Component</button>
</template>

// examples/react-nextjs/app/_components/TestCustomButton.tsx
'use client'

import type { ComponentPropsWithoutRef } from 'react'

import { QuilttButton } from '@quiltt/react'

type CustomButtonProps = ComponentPropsWithoutRef<'button'>

const CustomButton = ({ children, ...props }: CustomButtonProps) => {
  return (
    <button
      className="rounded-md bg-purple-500 px-4 py-2 text-white hover:bg-purple-900"
      {...props}
    >
      {children}
    </button>
  )
}

export const TestCustomButton = () => {
  return (
    <QuilttButton
      as={CustomButton}
      connectorId="connector"
      onExitSuccess={() => console.log('onExitSuccess')}
    >
      Launch with Custom Component
    </QuilttButton>
  )
}
export default TestCustomButton
