// examples/vue-nuxt/src/components/test-js-launcher.vue
<script setup lang="ts">

import { useQuilttConnector } from '@quiltt/vue'

const config = useRuntimeConfig()
const connectorId = config.public.quilttConnectorId

const { open } = useQuilttConnector(connectorId, {
  onEvent: (type) => console.log(`Event: ${type}`),
})
</script>

<template>
  <button type="button" class="launcher-button" @click="open">Launch with Javascript</button>
</template>

// examples/react-nextjs/src/app/_components/TestJSLauncher.tsx
'use client'

import { useQuilttConnector } from '@quiltt/react'

import { connectorId } from './quiltt-config'

export const TestJSLauncher = () => {
  const { open } = useQuilttConnector(connectorId, {
    onEvent: (type) => console.log(`Event: ${type}`),
  })

  return (
    <button type="button" className="launcher-button" onClick={open}>
      Launch with Javascript
    </button>
  )
}
export default TestJSLauncher
