// examples/vue-nuxt/src/components/test-custom-button.vue
<script setup lang="ts">

import { useQuilttConnector } from '@quiltt/vue'

const { open } = useQuilttConnector('connector', {
  onExitSuccess: () => console.log('onExitSuccess'),
})
</script>

<template>
  <button type="button" class="component-button" @click="open">Launch with Custom Component</button>
</template>

// examples/nextjs/app/components/TestCustomButton.tsx
'use client'

import { QuilttButton } from '@quiltt/react'

const CustomButton = ({ children, ...props }: any) => {
  return (
    <button
      className="bg-purple-500 hover:bg-purple-900 text-white py-2 px-4 rounded-md"
      {...props}
    >
      {children}
    </button>
  )
}

export const TestCustomButton = () => {
  return (
    <QuilttButton
      as={CustomButton}
      connectorId="connector"
      onExitSuccess={() => console.log('onExitSuccess')}
    >
      Launch with Custom Component
    </QuilttButton>
  )
}
export default TestCustomButton
